### PR TITLE
Adding constructors for basic and full auth

### PR DESCRIPTION
**Pull request by RabebOthmani**
hey @smithrobs , seems like users are expecting to init api auth details via constructors. Let me know if you have any objections to this . thanks

### CODE REVIEW

**Comment by smithrobs** [comment]
I'm unsure about 366941a - I took out the `System.IO` usage because of the possible trust issue, but since trust levels and CAS is deprecated in net core and this would be optional perhaps I am over-reacting...

**Comment by RabebOthmani** [comment]
Hummm, good point though

**Comment by RabebOthmani** [comment]
@smithrobs could you give this another quick look please? Thanks :)

**Comment by smithrobs** [comment]
👍 but can I be picky and request lower camel case for the params? `nexmoApiKey` instead of `NEXMO_API_KEY`, `nexmoApiSecret` instead of `NEXMO_API_SECRET`, and so on. That's what the majority of the lib is doing.

**Pull request merged**
